# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question_text2',
        ),
    ]
