# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 23:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20180508_1854'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Restaurants',
        ),
    ]
