# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20180508_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurants',
            old_name='question_text2',
            new_name='question_text',
        ),
        migrations.RemoveField(
            model_name='restaurants',
            name='pub_date',
        ),
    ]
