# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-09 00:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20180508_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Z_Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Restaurants',
        ),
    ]
