# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-11 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20180508_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=200, null=True)),
                ('food_type', models.CharField(max_length=200, null=True)),
                ('r_ingredients', models.CharField(max_length=1024, null=True)),
                ('r_time', models.CharField(max_length=200, null=True)),
                ('r_image', models.CharField(max_length=200, null=True)),
                ('r_rating', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
